/*
 * URBAN YUVA PRODUCT CATALOGUE
 * ------------------------------------------------------------
 * Edit this one file when you want to change a product.
 * Keep each `id` unique. Prices are written as plain numbers.
 */

const PRODUCTS = [
  {
    id: 1,
    name: "Core Oversized Tee",
    category: "T-Shirts",
    price: 699,
    originalPrice: 899,
    badge: "Bestseller",
    image: "images/core-oversized-tee.jpg",
    alt: "Black oversized men's T-shirt on a clean studio background",
    colors: ["Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 124,
    shortDescription: "Heavyweight comfort with an easy, drop-shoulder fit.",
    description: "A clean everyday tee cut in our relaxed campus fit. The structured cotton keeps its shape while the soft finish makes it comfortable from first lecture to late-night plans.",
    features: ["240 GSM cotton", "Drop-shoulder fit", "Pre-shrunk fabric", "Machine washable"]
  },
  {
    id: 2,
    name: "Shadow Graphic Tee",
    category: "T-Shirts",
    price: 799,
    originalPrice: 999,
    badge: "New",
    image: "images/shadow-graphic-tee.jpg",
    alt: "White men's streetwear T-shirt with a minimal black graphic",
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 86,
    shortDescription: "A monochrome statement tee with a soft, boxy shape.",
    description: "Made for repeat wear, this boxy tee pairs a minimal graphic with breathable cotton. Style it with cargos, denim or layered under an overshirt.",
    features: ["220 GSM cotton", "High-density print", "Boxy fit", "Bio-washed finish"]
  },
  {
    id: 3,
    name: "Varsity Overshirt",
    category: "Shirts",
    price: 999,
    originalPrice: 1299,
    badge: "Limited",
    image: "images/varsity-overshirt.jpg",
    alt: "Black men's varsity overshirt styled for a college streetwear look",
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
    reviews: 57,
    shortDescription: "A relaxed layer for instant after-class polish.",
    description: "The Varsity Overshirt gives you the structure of a shirt with the ease of a light jacket. Its roomy cut is designed to layer cleanly over your favourite tee.",
    features: ["Midweight twill", "Relaxed fit", "Two utility pockets", "Metal snap buttons"]
  },
  {
    id: 4,
    name: "Utility Cargo Pants",
    category: "Bottoms",
    price: 999,
    originalPrice: 1399,
    badge: "Trending",
    image: "images/utility-cargo-pants.jpg",
    alt: "Black men's utility cargo pants with multiple pockets",
    colors: ["Black", "Stone"],
    sizes: ["28", "30", "32", "34", "36"],
    rating: 4.8,
    reviews: 102,
    shortDescription: "Roomy cargos built for everyday movement and storage.",
    description: "A straight-relaxed cargo with useful pockets and an adjustable hem. The durable cotton blend stays comfortable through long days on campus.",
    features: ["Cotton stretch twill", "Six functional pockets", "Adjustable hem", "Relaxed straight fit"]
  },
  {
    id: 5,
    name: "Everyday Relaxed Joggers",
    category: "Bottoms",
    price: 899,
    originalPrice: 1199,
    badge: "Campus Pick",
    image: "images/relaxed-joggers.jpg",
    alt: "Dark grey relaxed men's joggers for casual everyday wear",
    colors: ["Charcoal", "Black"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviews: 73,
    shortDescription: "Clean tapered joggers without the gym-only look.",
    description: "Soft enough for slow mornings and sharp enough for the rest of your day. These joggers use a neat tapered leg and low-profile detailing for easy styling.",
    features: ["Loopback cotton", "Tapered relaxed fit", "Zipped pockets", "Adjustable drawcord"]
  },
  {
    id: 6,
    name: "Monochrome Polo",
    category: "T-Shirts",
    price: 849,
    originalPrice: 1099,
    badge: "Smart Casual",
    image: "images/monochrome-polo.jpg",
    alt: "Minimal black men's polo shirt photographed in a studio",
    colors: ["Black", "Off White"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 68,
    shortDescription: "A modern polo that works from presentations to plans.",
    description: "A stripped-back polo with a clean collar, comfortable stretch and no loud branding. It is the easiest way to make jeans or trousers look intentional.",
    features: ["Premium cotton pique", "Modern regular fit", "Ribbed collar", "Soft stretch"]
  },
  {
    id: 7,
    name: "Boxy Oxford Shirt",
    category: "Shirts",
    price: 949,
    originalPrice: 1199,
    badge: "New",
    image: "images/boxy-oxford-shirt.jpg",
    alt: "White boxy-fit men's Oxford shirt with minimal styling",
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 41,
    shortDescription: "Crisp Oxford texture in a relaxed, untucked cut.",
    description: "Designed shorter and roomier than a formal shirt, this Oxford looks right worn open, buttoned or layered. A dependable choice for days that need a little extra effort.",
    features: ["Textured cotton", "Boxy fit", "Reinforced collar", "Easy-care finish"]
  },
  {
    id: 8,
    name: "Campus Essential Tee",
    category: "T-Shirts",
    price: 599,
    originalPrice: 749,
    badge: "Everyday",
    image: "images/campus-essential-tee.jpg",
    alt: "Charcoal men's essential crew-neck T-shirt for college wear",
    colors: ["Charcoal", "White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviews: 156,
    shortDescription: "The no-fuss crew neck made for a weekly rotation.",
    description: "A reliable regular-fit tee with a smooth neckline and breathable feel. Buy one for the first wear; come back because it holds up.",
    features: ["180 GSM cotton", "Regular fit", "Reinforced neckline", "Colour-fast finish"]
  }
];

